# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "DenyList",
    "DenyListDaac",
    "DenyListRs",
]

@typing.final
class DenyList:
    def __new__(cls, words: typing.Sequence[builtins.str]) -> DenyList:
        r"""
        constructor
        # Errors
        * aho-corasic errors (too long patterns)
        """
    def is_match(self, s: builtins.str) -> builtins.bool: ...
    def scan_str(self, txt: builtins.str) -> builtins.bool: ...
    def scan(self, args: dict) -> builtins.bool: ...
    def scan_any(self, value: typing.Any) -> builtins.bool:
        r"""
        scans dict,str,list
        """

@typing.final
class DenyListDaac:
    def __new__(cls, words: typing.Sequence[builtins.str]) -> DenyListDaac:
        r"""
        constructor
        # Errors
        * daachorse errors (e.g. too long patterns)
        """
    def is_match(self, s: builtins.str) -> builtins.bool: ...
    def scan_str(self, txt: builtins.str) -> builtins.bool: ...
    def scan(self, args: dict) -> builtins.bool: ...
    def scan_any(self, value: typing.Any) -> builtins.bool:
        r"""
        scans dict,str,list
        """

@typing.final
class DenyListRs:
    def __new__(cls, words: typing.Sequence[builtins.str]) -> DenyListRs:
        r"""
        constructor
        # Errors
        * regex problems (should not happen with simple match)
        """
    def is_match(self, s: builtins.str) -> builtins.bool: ...
    def scan_str(self, txt: builtins.str) -> builtins.bool: ...
    def scan(self, args: dict) -> builtins.bool: ...
    def scan_any(self, value: typing.Any) -> builtins.bool: ...

