# Type stubs for pyahocorasick
# https://github.com/WojciechMula/pyahocorasick

from typing import Any, Iterable, Iterator, Tuple, overload

STORE_ANY: int
STORE_INTS: int
STORE_LENGTH: int
STORE_VALUE: int

KEY_STRING: int
KEY_INTEGER: int

class Automaton:
    """
    Aho-Corasick automaton for multi-pattern string matching.
    """
    
    @overload
    def __init__(self, kind: int = STORE_ANY, key: int = KEY_STRING) -> None: ...
    @overload
    def __init__(self, kind: int = STORE_ANY, key: int = KEY_STRING, *, version: int) -> None: ...
    
    def add_word(self, word: str, value: Any) -> bool: ...
    def remove_word(self, word: str) -> bool: ...
    def clear(self) -> None: ...
    def make_automaton(self) -> None: ...
    def dump(self, to_str: bool = True) -> str: ...
    
    @property
    def kind(self) -> int: ...
    @property
    def key(self) -> int: ...
    @property
    def version(self) -> int: ...
    @property
    def longest_word(self) -> int: ...
    @property
    def shortest_word(self) -> int: ...
    @property
    def value_count(self) -> int: ...
    @property
    def word_count(self) -> int: ...
    @property
    def kind_name(self) -> str: ...
    @property
    def key_name(self) -> str: ...
    
    def get(self, word: str) -> Any: ...
    def exists(self, word: str) -> bool: ...
    def match(self, word: str) -> bool: ...
    
    @overload
    def iter(self, text: str) -> Iterator[Tuple[int, Any]]: ...
    @overload
    def iter(self, text: str, start: int) -> Iterator[Tuple[int, Any]]: ...
    @overload
    def iter(self, text: str, start: int, end: int) -> Iterator[Tuple[int, Any]]: ...
    @overload
    def iter_long(self, text: str) -> Iterator[Tuple[int, Any]]: ...
    @overload
    def iter_long(self, text: str, start: int) -> Iterator[Tuple[int, Any]]: ...
    @overload
    def iter_long(self, text: str, start: int, end: int) -> Iterator[Tuple[int, Any]]: ...
    
    def iter_empty(self) -> Iterator[Tuple[int, Any]]: ...
    
    def extend(self, words: Iterable[str]) -> None: ...
    def add_words(self, words: Iterable[str]) -> None: ...
    
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...
    def __reduce__(self) -> Tuple[type, bytes]: ...
